//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLAdModel.DAL {
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SkyNetExoEntities : DbContext {
        public SkyNetExoEntities()
            : base("name=SkyNetExoEntities") {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder) {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<departement> departement { get; set; }
        public virtual DbSet<employe> employe { get; set; }
    }
}
